### ISSUE TITLE
exits with error when trying to write to logfile when k8s api is not available and rbac-manager is running in a ro fs

### ISSUE THREAD

**Issue by looztra** [FairwindsOps/rbac-manager#104]
Using `rbac-manager` v0.8.1

We are running `rbac-manager` with `securityContext.readOnlyRootFilesystem: true` in a GKE cluster and when we update the master version or a configuration (of the master), the `rbac-manager` starts to crashloop with errors :

```
Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=1069, ErrCode=NO_ERROR, debug=""
log: exiting because of error: log: cannot create log: open /tmp/rbac-manager.rbac-manager-66c45f4895-5rwrh.unknownuser.log.ERROR.20191112-084947.1: no such file or directory
```

We setup a dirty workaround to use an `emptyDir` for `/tmp` but that would be nice if `rbac-manager` could handle connection to the k8s api in a failsafe manner (or if at least it could avoid trying to log to files when an Error occurs)

**Comment by sudermanjr** [comment]
Thanks for reporting this. 

I'm surprised we are seeing it try to log to a file.  I already am planning to do a once-over on the logging in general. I will add this to that task.

**Comment by mjhuber** [comment]
seeing this same error sporadically after upgrading to Kubernetes 1.15

**Comment by lucasreed** [comment]
I'll look into why it's trying to log out to a file. I don't think it's a terrible thing if rbac-manager is killed and restarted during maintenance since it doesn't hold any state and will pick up where it left off when it starts back up, but I am concerned if it stays in a CrashLoop state consistently.

@looztra without the `emptyDir` workaround does rbac-manager eventually recover during your upgrade/maintenance windows? I would expect that it would start fine after the control-plane becomes available again, but I'd be interested to hear if that's not the case.

For reference, we saw this issue crop up in a GKE cluster as well but after the upgrade completed, it worked fine without manual intervention.

**Comment by lucasreed** [comment]
Done some work on this and found that it's coming from klog dependency. I have a fix in progress I hope. Testing it now.

https://github.com/kubernetes/klog/issues/89

**Comment by lucasreed** [comment]
In testing the PR mentioned above, errors are now printed to stderr instead of attempting to open a file. This also prevents the container from crashing which is preferred (the watchers recover post upgrade from what I can tell).
