### ISSUE TITLE
RBAC-Manager Pod queries

### ISSUE THREAD

**Issue by VarunTyagi86** [FairwindsOps/rbac-manager#113]
1  If due to any issue or upgrade RBAC-manager pod gets stopped will it impact the role bindings it created?
2  Currently, there is only one Pod of RBAC-Manager that runs, is it possible to run multiple replicas of RBAC-Manager pods? Will it not cause conflict while listening to RBAC Definitions ? If it is doable please let me know what are prod specific recommendations for using RBAC-Manager.

**Comment by sudermanjr** [comment]
1. If the pod gets stopped, it will not cause any issues with the role bindings being created. If there are any modifications to your settings, the Rbac-manager pod will reconcile them when it starts back up.

2. We have considered adding leader election to allow running multiple pods, however it has not been a priority due to the answer I gave to part 1. A brief downtime in the rbac-manager pod will not affect anything in-cluster, so there is not a strong need for an HA deployment. We run a single rbac-manager pod in production environments.

**Comment by VarunTyagi86** [comment]
Thank you Andrew, that certainly helps!!

Do you know tentatively by when this "We have considered adding leader election to allow running multiple pods" will be done?

**Comment by sudermanjr** [comment]
Probably not any time in the near future due to the extremely low priority. I'll file an issue for it and mention it so that you can track it.

**Comment by VarunTyagi86** [comment]
Thank you.
