### ISSUE TITLE
[feature request] namespace regexes

### ISSUE THREAD

**Issue by Art3mK** [FairwindsOps/rbac-manager#129]
Hey 👋 

It would be nice to be able to match namespaces based on name, not only on labels. Same feature was requested in #47, but it was closed for some reason.

Any thoughts on that, would it be hard to implement?

Thanks!

**Comment by lucasreed** [comment]
Thanks for bringing this up! Could you describe a use case you would need this feature for? I can't think of a reason that label matching wouldn't be preferable because it is more explicit in how permissions are granted.

In #47 the issue was to workaround helm-created namespaces, but helm 3 removed the capability of creating namespaces which means you have to create them ahead of time anyway allowing you to label them as needed for rbac-manager.

**Comment by Art3mK** [comment]
They implement that back, will be available in helm 3.2, see [#7648](https://github.com/helm/helm/pull/7648) 🙂 

so my use case is pretty simple - binding roles for devs in dynamic environments, created by CI service.

**Comment by sudermanjr** [comment]
> so my use case is pretty simple - binding roles for devs in dynamic environments, created by CI service.

I don't really understand why this is no accomplished by a labelSelector. 

In the end, this is not as simple of an ask as just adding a regex match. Due to the creation of ServiceAccounts, and the namespace being in the Subject field of the bindings, this will be a not-insignificant change to the ServiceAccount logic. 

Since it is not a simple change, and the desired functionality is already achievable, I'm leaning towards not implementing this.

**Comment by Art3mK** [comment]
yeah, certainly some workarounds are possible, like labeling namespace after deploying helm chart. This is just one more thing to remember to do.

I don't have strong arguments why I need that, just a nice feature to have :)

**Comment by sudermanjr** [comment]
Thanks for your feedback. We talked about it and we don't think this is something we would like to add at this time.
