### ISSUE TITLE
go get fails with `invalid github.com import path` error

### ISSUE THREAD

**Issue by mzeevi** [FairwindsOps/rbac-manager#356]
### What happened?

Hello,

I have a use-case where I want to create a RBAC Manager CR in another code and since I'm working in an air-gap environment I need to get the packages into my network. 

I did the following:

```
git clone https://github.com/FairwindsOps/rbac-manager.git
cd rbac-manager
go get github.com/fairwindsops/rbac-manager
```

And got the following error:

```
go: github.com/fairwindsops/rbac-manager: invalid github.com import path "github.com/fairwindsops"
```

I then tried:

```
go get github.com/FairwindsOps/rbac-manager
```

And got this error:

```
go: github.com/FairwindsOps/rbac-manager@v1.4.2: parsing go.mod:
	module declares its path as: github.com/fairwindsops/rbac-manager
	        but was required as: github.com/FairwindsOps/rbac-manager
```

Anything I'm missing here?

Thanks!

### What did you expect to happen?

Packages to be downloaded locally.

### How can we reproduce this?

Explained above.

### Version

go version go1.18.3 linux/amd64

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Hmmm, that's interesting. I don't think anyone has tried to use rbac-manager as a package before. We probably need to change some things structurally if that's something we are going to support.

If you're just trying to get the custom resource definition, could you try and import of `github.com/fairwindsops/rbac-manager/pkg/apis` and then run a `go mod tidy`, rather than trying to `go get` directly?

**Comment by mzeevi** [comment]
Seems to be doing the trick, thanks!
